import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { i18n, type Locale } from 'lib/i18n-config';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html className="h-full" lang={params.lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
